apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-test.fullname" . }}
  labels:
    {{- include "django-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: test-port
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "django-test.selectorLabels" . | nindent 4 }}
